//Seleziona il primo oggetto.
selected = 0;
//Definisci qual è il numero massimo, ad esempio se arriva a stack_names[9] scrivi 9.
totalitems = 48;
//Definisci l'array con tutti i nomi degli oggetti da fare spawnare.
stack_names[0] = o_squadra_sin;
stack_names[1] = o_squadra_des;
stack_names[2] = o_gomma_piccola;
stack_names[3] = o_gomma_grande;
stack_names[4] = o_carta_palla;
stack_names[5] = o_moneta;
stack_names[6] = o_libro_mate;
stack_names[7] = o_temperino;
stack_names[8] = o_matita;
stack_names[9] = o_paracadute;
stack_names[10] = o_wall_norm;
stack_names[11] = o_totem_A;
stack_names[12] = o_totem_B;
stack_names[13] = o_totem_C;
stack_names[14] = o_totem_D;
stack_names[15] = o_totem_E;
stack_names[16] = o_totem_F;
stack_names[17] = o_totem_G;
stack_names[18] = o_totem_H;
stack_names[19] = o_totem_I;
stack_names[20] = o_totem_J;
stack_names[21] = o_radio_palla;
stack_names[22] = o_radio_cubo;
stack_names[23] = o_radio_triangolo;
stack_names[24] = o_radio_triangolo_2;
stack_names[25] = o_radio_palla_grande;
stack_names[26] = o_generale;
stack_names[27] = o_bomba;
stack_names[28] = o_esplosivo;
stack_names[29] = o_clock_sec;
stack_names[30] = o_clock_min;
stack_names[31] = o_clock_hou;
stack_names[32] = o_count_ent;
stack_names[33] = o_bott_red;
stack_names[34] = o_lock_red;
stack_names[35] = o_chiave_red;
stack_names[36] = o_bott_blue;
stack_names[37] = o_lock_blue;
stack_names[38] = o_chiave_blue;
stack_names[39] = o_bott_green;
stack_names[40] = o_lock_green;
stack_names[41] = o_chiave_green;
stack_names[42] = o_CD;
stack_names[43] = o_wall_norm_L_D;
stack_names[44] = o_wall_norm_R_D;
stack_names[45] = o_wall_norm_R_U;
stack_names[46] = o_wall_norm_L_U;
stack_names[47] = o_wall_norm_move_h;
stack_names[48] = o_wall_norm_stomp_h_r;
//Disattiva il mouse normale visto che viene generato automaticamente.
window_set_cursor(cr_none);
//Apri il file di salvataggio, carica il record e chiudi il file.
ini_open("savefile.ini");
stack.blocksr = ini_read_real("Stack",room_get_name(room),"0");
ini_close();
